<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="0" total="6" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-28T11:22:27 EST" name="Default suite" finished-at="2021-12-28T11:24:34 EST" duration-ms="127625">
    <groups>
      <group name="smokeSuite">
        <method signature="CreateContactTestCase.CreateContact()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" name="CreateContact" class="practiseTestNG.CreateContactTestCase"/>
      </group> <!-- smokeSuite -->
      <group name="regressionSuite">
        <method signature="CreateContactTestCase.CreateContact()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" name="CreateContact" class="practiseTestNG.CreateContactTestCase"/>
      </group> <!-- regressionSuite -->
    </groups>
    <test started-at="2021-12-28T11:22:27 EST" name="Default test" finished-at="2021-12-28T11:24:34 EST" duration-ms="127625">
      <class name="practiseTestNG.CreateContactTestCase">
        <test-method is-config="true" signature="dbConnection()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:22:27 EST" name="dbConnection" finished-at="2021-12-28T11:22:27 EST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dbConnection -->
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:22:27 EST" name="openBrowser" finished-at="2021-12-28T11:22:41 EST" duration-ms="14224" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="loginAplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:22:41 EST" name="loginAplication" finished-at="2021-12-28T11:22:59 EST" duration-ms="17966" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAplication -->
        <test-method retried="true" signature="CreateContact()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:22:59 EST" name="CreateContact" finished-at="2021-12-28T11:23:27 EST" duration-ms="27380" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practiseTestNG.CreateContactTestCase.CreateContact(CreateContactTestCase.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateContact -->
        <test-method is-config="true" signature="logoutApplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:23:27 EST" name="logoutApplication" finished-at="2021-12-28T11:23:29 EST" duration-ms="2634" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutApplication -->
        <test-method is-config="true" signature="loginAplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:23:29 EST" name="loginAplication" finished-at="2021-12-28T11:23:32 EST" duration-ms="2721" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAplication -->
        <test-method retried="true" signature="CreateContact()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:23:32 EST" name="CreateContact" finished-at="2021-12-28T11:23:40 EST" duration-ms="7695" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practiseTestNG.CreateContactTestCase.CreateContact(CreateContactTestCase.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateContact -->
        <test-method is-config="true" signature="logoutApplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:23:40 EST" name="logoutApplication" finished-at="2021-12-28T11:23:42 EST" duration-ms="2372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutApplication -->
        <test-method is-config="true" signature="loginAplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:23:42 EST" name="loginAplication" finished-at="2021-12-28T11:23:45 EST" duration-ms="2946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAplication -->
        <test-method retried="true" signature="CreateContact()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:23:45 EST" name="CreateContact" finished-at="2021-12-28T11:23:56 EST" duration-ms="11209" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practiseTestNG.CreateContactTestCase.CreateContact(CreateContactTestCase.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateContact -->
        <test-method is-config="true" signature="logoutApplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:23:56 EST" name="logoutApplication" finished-at="2021-12-28T11:23:58 EST" duration-ms="2051" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutApplication -->
        <test-method is-config="true" signature="loginAplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:23:58 EST" name="loginAplication" finished-at="2021-12-28T11:24:01 EST" duration-ms="2752" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAplication -->
        <test-method retried="true" signature="CreateContact()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:24:01 EST" name="CreateContact" finished-at="2021-12-28T11:24:09 EST" duration-ms="8485" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practiseTestNG.CreateContactTestCase.CreateContact(CreateContactTestCase.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateContact -->
        <test-method is-config="true" signature="logoutApplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:24:09 EST" name="logoutApplication" finished-at="2021-12-28T11:24:11 EST" duration-ms="2039" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutApplication -->
        <test-method is-config="true" signature="loginAplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:24:11 EST" name="loginAplication" finished-at="2021-12-28T11:24:15 EST" duration-ms="3319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAplication -->
        <test-method signature="CreateContact()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:24:15 EST" name="CreateContact" finished-at="2021-12-28T11:24:23 EST" duration-ms="8288" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at practiseTestNG.CreateContactTestCase.CreateContact(CreateContactTestCase.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateContact -->
        <test-method is-config="true" signature="logoutApplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:24:23 EST" name="logoutApplication" finished-at="2021-12-28T11:24:26 EST" duration-ms="2398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutApplication -->
        <test-method is-config="true" signature="loginAplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:24:26 EST" name="loginAplication" finished-at="2021-12-28T11:24:28 EST" duration-ms="2439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAplication -->
        <test-method signature="demo()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:24:28 EST" name="demo" finished-at="2021-12-28T11:24:28 EST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demo -->
        <test-method is-config="true" signature="logoutApplication()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:24:28 EST" name="logoutApplication" finished-at="2021-12-28T11:24:33 EST" duration-ms="4857" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutApplication -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:24:33 EST" name="closeBrowser" finished-at="2021-12-28T11:24:34 EST" duration-ms="1144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="CloseDBConnection()[pri:0, instance:practiseTestNG.CreateContactTestCase@4d5b6aac]" started-at="2021-12-28T11:24:35 EST" name="CloseDBConnection" finished-at="2021-12-28T11:24:35 EST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseDBConnection -->
      </class> <!-- practiseTestNG.CreateContactTestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
